# Default initial positions for panda's ros2_control fake system

initial_positions:
  panda_finger_joint1: 0
  panda_joint1: 0
  panda_joint2: -75
  panda_joint3: 0
  panda_joint4: -135
  panda_joint5: 0
  panda_joint6: 90
  panda_joint7: 45
  
  #기존 0 0 0 0 0 0 0
